pipeline:
  changelog:
    image: lawnchairlauncher/drone-changelog:dev
    output: changelog.txt
    volumes:
      - /opt/drone/cache:/cache
    when:
      event: push
  build:
    image: runmymind/docker-android-sdk:ubuntu-standalone
    secrets: [ store_password, key_password ]
    environment:
      - MAJOR_MINOR=alpha
      - TRAVIS=true
      - TRAVIS_BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - TRAVIS_EVENT_TYPE=${DRONE_BUILD_EVENT}
    commands:
      - bash ./gradlew assembleAospCiOptimized;
  deploy:
    image: lawnchairlauncher/drone-telegram:dev
    secrets: [ bot_token, channel_id ]
    apk_path: build/outputs/apk/aospCi/optimized/LawnchairWIP-aosp-ci-optimized.apk
    mapping_path: build/outputs/mapping/aospCi/optimized/mapping.txt
    channel_id: "-1001390439747"
    environment:
      - MAJOR_MINOR=v2-alpha
    when:
      event: push
      status: success
  telegram:
      image: appleboy/drone-telegram:latest
      secrets: [ telegram_token ]
      to: "-1001092684628"
      message: >
        {{#success build.status}}
          Build {{build.number}} succeeded. Good job mate!
        {{else}}
          Build {{build.number}} failed. Fix me please sir!
        {{/success}}

branches:
  include: alpha
  exclude: [ l10n_alpha2, v2-alpha ]
