language: android
sudo: required
jdk: oraclejdk8

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

env:
  global:
  - ANDROID_API=26
  - EMULATOR_API=25
  - ANDROID_BUILD_TOOLS=28.0.3
  - ADB_INSTALL_TIMEOUT=5 # minutes

android:
  components:
  - build-tools-28.0.3
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - extra-android-support # because I'm use support library
  - extra-android-m2repository # because I'm use support library
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+

before_install:
- chmod +x gradlew
- ./gradlew dependencies || true
- yes | sdkmanager "platforms;android-28"

script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"

